### PR TITLE
Update Django to v2

### LINKED ISSUE #162: Migrate Django 1.11 to 2.2 LTS
Examine which changes are necessary and migrate the current development state to the new LTS version of Django.

### PR DESCRIPTION
**Pull request by svenseeberg**
This PR:
* Removes version fixations for libs in setup.py
* Adds on_delete=modules.CASCADE to several foreign keys in the Extra and Feedback classes
* Adds some disable pylint comments
* Fix error handlers

Fixes  #162

### CODE REVIEW

**Comment by svenseeberg** [comment]
Do we need any further changes for this PR?

**Comment by timoludwig** [comment]
> A point for discussion: Is on_delete=CASCADE the right thing to do for feedback?

I think yes. As soon as an object gets deleted, the respective feedback is probably not relevant anymore.

**Comment by svenseeberg** [comment]
The CMS seems to start correctly now. Everybody is welcome to search for problems and errors.

**Comment by svenseeberg** [comment]
After dropping the database, creating a new one with a fresh migration, I get the following errors:

```
Performing system checks...

System check identified no issues (0 silenced).
August 19, 2019 - 16:04:24
Django version 2.2.4, using settings 'backend.settings'
Starting development server at http://localhost:8000/
Quit the server with CONTROL-C.
Internal Server Error: /regions/
Traceback (most recent call last):
  File "/home/sven/Code/integreat-cms-django/.venv/lib64/python3.6/site-packages/Django-2.2.4-py3.6.egg/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/sven/Code/integreat-cms-django/.venv/lib64/python3.6/site-packages/Django-2.2.4-py3.6.egg/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
TypeError: 'User' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sven/Code/integreat-cms-django/.venv/lib64/python3.6/site-packages/Django-2.2.4-py3.6.egg/django/db/models/fields/related_descriptors.py", line 393, in __get__
    rel_obj = self.related.get_cached_value(instance)
  File "/home/sven/Code/integreat-cms-django/.venv/lib64/python3.6/site-packages/Django-2.2.4-py3.6.egg/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'profile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sven/Code/integreat-cms-django/.venv/lib64/python3.6/site-packages/Django-2.2.4-py3.6.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "cms_userprofile" does not exist
LINE 1: ...ser_id", "cms_userprofile"."organization_id" FROM "cms_userp...
```

**Comment by svenseeberg** [comment]
The previous error was due to a not clean database. After dropping everything and recreating as described in the README it works fine.

**Pull request merged**
