### PR TITLE
Disable Heading 1 style in certain TinyMCE fields

### PR DESCRIPTION
**Pull request by aitorres**
### Short description
This PR disables the possibility of using the Heading 1 style in TinyMCE fields for text and descriptions, throwing a validation error if the `<h1>` tags are (manually) inserted into the field's content.

### Proposed changes
First, the PR removes the possibility of selecting "Heading 1" as a style in certain TinyMCE fields by manually overriding which styles are visible in the TinyMCE styles list. The affected tinyMCE instances are in the following templates:

- `cms/templates/events/event_form.html`
- `cms/templates/pages/page_form.html`
- `cms/templates/pages/page_sbs.html`
- `cms/templates/pois/poi_form.html`

Second, the PR adds a specific `clean_<field>` method to the Django Forms being used in the aforementioned templates, that checks for the presence of `<h1>` tags in their fields and, if found, raises a validation error with an appropriate message.

The forms changed are:

- EventTranslationForm (field: description)
- PageTranslationForm (field: text)
- POITranslationForm (field: description)

These three forms are used in the templates above. This way, we prevent the use of "Heading 1" styles both in front-end and in back-end.

### Misc notes

I am not sure about the validation error message I used, which is: "Use of Heading 1 style not allowed."

Any suggestions would be accepted and changed into the Pull Request.

Also, ich spreche nicht Deutsch :-P so I wasn't able to add a properly translated string to the DE locale files. That would be a pending thing to do. If you can provide an equivalent message in Deutsch, I can add it to the proper locale file.

### Resolved issues

Fixes: #516

### CODE REVIEW

**Review by timoludwig — CHANGES_REQUESTED** [review]
Amazing, thank you for your contribution :heart: 

The form validation works as expected, thanks! However, I didn't get the tinymce setting to work. When I navigate to one of the forms, I can still select "Heading 1" as format. I think this is because we don't use the `formatselect` dropdown, but the `styleselect` instead. Thus, we have to adjust the option `style_formats` instead of `block_formats`. So i propose to remove heading 1 form the [default value of style_formats](https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats) and include this array in the tinymce init function.

As for the translation, I propose the German translation:
> Bitte benutzen Sie keine Überschrift 1 in diesem Feld.

Thanks again for your effort! I added the `hacktoberfest`-tag to our repository to make sure PRs are eligible for this year's challenge.

**Comment by aitorres** [comment]
Hey @timoludwig! Thank you so much for your comments! I'll be doing the proposed changes during the day and I'll let you know.

**Comment by aitorres** [comment]
Hello @timoludwig! Sorry for the delay, I've pushed a couple of commits for both adding the translated string to the deutsch locale and explicitly using `styles_format`, I think this would solve the issue. Let me know if there's anything else I could do!

**Review by timoludwig — APPROVED** [review]
Thank you! Now everything works as expected. :+1:

**Pull request merged**
